# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
#org.gradle.parallel=true
org.gradle.caching=false
org.gradle.caching.debug=false
org.gradle.parallel=false
#org.gradle.configureondemand=true

# Mod properties
mod.version=4.1.0
mod.group=eu.midnightdust
mod.id=cullleaves
mod.name=CullLeaves

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title=[VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets=[VERSIONED]

# Mod setup
deps.fabric_loader=0.17.3
deps.fabric_version=[VERSIONED]

deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.midnightlib_version=1.9.0-alpha.1
deps.sodium_version=mc1.21.8-0.7.0

# Publishing
publish.modrinth=GNxdLCoP
publish.curseforge=423254