org.gradle.jvmargs=-Xmx4096M

minecraft_version=1.21.6
yarn_mappings=1.21.6+build.1
enabled_platforms=fabric,neoforge

archives_base_name=cullleaves
mod_version=4.0.5
maven_group=eu.midnightdust
release_type=release
curseforge_id=423254
modrinth_id=GNxdLCoP

midnightlib_version=1.7.4+1.21.6
sodium_version=mc1.21.6-0.6.13

fabric_loader_version=0.16.14
fabric_api_version=0.127.0+1.21.6

neoforge_version=21.6.0-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4

quilt_loader_version=0.18.9
quilt_fabric_api_version=7.0.6+0.85.0-1.20.1
