modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "cullleaves"
version = "${version}"
displayName = "CullLeaves"
authors = "Motschen, TeamMidnightDust"
description = '''
Adds culling to leaf blocks, providing a huge performance boost over vanilla.
'''
logoFile = "icon.png"

[[mixins]]
config = "cullleaves.mixins.json"

[[mixins]]
config = "cullleaves-neoforge.mixins.json"

[[dependencies.cullleaves]]
modId = "neoforge"
required = true
versionRange = "[20.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cullleaves]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cullleaves]]
modId = "midnightlib"
required = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "CLIENT"